version: '3.8'

services:
  logger-message-queue-api:
    build:
      context: ./LoggerMessageQueueApi

  api-gateway:
    build:
      context: ./Gateway

  logger:
    build:
      context: ./Logger

  notes:
    build:
      context: ./Notes
