# app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  KC_DB_PASSWORD: "{{ .Values.secrets.KC_DB_PASSWORD }}"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.secrets.KC_BOOTSTRAP_ADMIN_PASSWORD }}"
  main_database_user: "{{ .Values.secrets.main_database_user }}"
  main_database_password: "{{ .Values.secrets.main_database_password }}"
  jwt_secret: "{{ .Values.secrets.jwt_secret }}"
  
  spring.datasource.password: "{{ .Values.secrets.main_database_password }}"
