spring.application.name=Notes
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/myrealm
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL}
eureka.client.instance.prefer-ip-address=true
