spring.datasource.url=jdbc:postgresql://postgres-logs:5432/logsdb
spring.datasource.username=loguser
spring.datasource.password=logpassword

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.max-attempts=10

logging.level.fi.breakwaterworks=DEBUG
