spring.application.name=LoadBalancer
server.port: ${EUREKA_SERVER_PORT}

eureka.client.register-with-eureka= false
eureka.client.fetch-registry= false

management.endpoints.web.exposure.include=health
management.health.livenessstate.enabled=true
