spring.application.name=Logger
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Correct the data source URL by referencing the correct environment variables
spring.datasource.url=${DATABASE_HOST}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# Eureka configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL}
eureka.client.instance.prefer-ip-address=true

spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
spring.rabbitmq.username=${RABBIT_MQ_USER}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}
