spring.application.name=${SPRING_APP_NAME:Opportunities}
server.port=8083

# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/opportunitiesdb}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true

# Security
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/auth/realms/crm/protocol/openid-connect/certs}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
